.github/workflows/docs.yml

Adding poetry to docs action

---

.github/workflows/docs.yml

Change github action to use poetry

---

motion/examples/cooking/triggers/search.py

Modifying example to follow infer context return

---

motion/examples/cooking/dashboard.py

remove redundant line

---

mkdocs.yml

Extra files for mkdocs (images)

---

.github/workflows/docs.yml
mkdocs.yml

Make mkdocs

---

.github/workflows/docs.yml
docs/tutorials/recipe/starter.md
mkdocs.yml

Trying to make mkdocs work with images

---

poetry.lock
pyproject.toml

Adding coverage

---

motion/cursor.py
tests/test_cursor.py

When `set` provides the wrong types for values, we should show a more helpful error. This PR does that.
Closes #115
Please make sure that you have completed the following items before submitting this pull request:

More helpful error messages

---

motion/entry.py
motion/store.py
tests/test_python_api.py

Allows for isolation of triggers during testing

---

Makefile
motion/cli.py

- Added error reporting for minimum python version not found on host
- Fix mconfig.py filepath
n/a
n/a
n/a

Add error reporting for common install failures

---

motion/cli.py
motion/execute.py

CLI sys path set

---

docs/vis.md
motion/cli.py

Change from `motion vis filename::c` to `motion vis filename:c`

Change vis command

---

motion/cli.py

Remove period from message

---

.github/workflows/ci.yml
README.md
docker-compose.yml
docs/api/component.md
docs/examples/design-patterns.md
docs/getting-started/concepts.md
docs/vis.md
mkdocs.yml
motion/__init__.py
motion/component.py
motion/execute.py
motion/fit_task.py
motion/instance.py
motion/serverless/modal_wrapper.py
motion/utils.py
poetry.lock
pyproject.toml
tests/component/test_bad_components.py
tests/component/test_counter.py
tests/component/test_multiple_routes.py
tests/component/test_params.py
tests/component/test_type_check.py
tests/component/test_varying_batch.py
tests/conftest.py
tests/parallel/test_two_instance.py
tests/state/test_db_conn.py
tests/state/test_model.py
tests/test_simple_pipeline.py

This PR allows multiple instances to share state, enabling a distributed setting. We introduce a Redis state sharing mechanism and allow each fit op to have its own process.
* Closes #142 
* Closes #140 
* Closes #131
* Closes #145
* Closes #136
Please make sure that you have completed the following items before submitting this pull request:

V3? V4? Of Motion!

---

pyproject.toml

Downgrade cloudpickle

---

motion/fit_task.py

Pickle outstanding items in a batch before adding them back to a queue

---

motion/execute.py
motion/fit_task.py

Change from signals to multiprocessing events

---

motion/execute.py

Making sure version is always an int

---

motion/fit_task.py
motion/instance.py
tests/state/test_flush_fit.py

Make fit processes daemon processes

---

docs/api/component-instance.md
motion/execute.py
motion/fit_task.py
motion/instance.py
motion/route.py
poetry.lock
pyproject.toml
tests/conftest.py
tests/parallel/test_async.py
tests/test_fastapi.py

This PR creates an `arun` method for the component instance, which allows async ops to be defined.
Closes #168 
Please make sure that you have completed the following items before submitting this pull request:

Create `arun` method

---

motion/component.py
motion/utils.py
tests/parallel/test_many_keys.py

Allowing multiple route keys

---

motion/fit_task.py
tests/parallel/test_broken_fit.py

Closes #175. Wrap the fit call in a try-catch-finally, and release lock in the finally.

Fail gracefully in fit function

---

motion/fit_task.py

Format exception

---

motion/execute.py
motion/instance.py
tests/state/test_model.py

Adding ignore cache functionality.

---

motion/execute.py

Fix bug that doesnt pass in running param to restarted processes

---

motion/server/fit_task.py
motion/utils.py
tests/component/test_counter.py
tests/parallel/test_broken_fit.py

Raising exception from fit process in main thread

---

motion/component.py
motion/execute.py
motion/utils.py
tests/state/test_write.py

Adding instance id to be exposed in the state

---

docs/examples/design-patterns.md
motion/component.py
motion/execute.py
motion/instance.py
tests/component/test_disabled_instance.py

Ability to create disabled instances

---

motion/component.py

Reword changes

---

docs/api/component-instance.md
docs/api/component.md
docs/api/props-and-state.md
docs/getting-started/concepts.md
docs/index.md
docs/tools/vis.md
mkdocs.yml
motion/component.py
motion/dicts.py
motion/execute.py
motion/instance.py
motion/migrate.py
motion/route.py
motion/server/update_task.py
motion/utils.py
tests/component/test_bad_components.py
tests/component/test_counter.py
tests/component/test_disabled_instance.py
tests/component/test_multiple_routes.py
tests/component/test_params.py
tests/parallel/test_async.py
tests/parallel/test_broken_fit.py
tests/parallel/test_many_keys.py
tests/parallel/test_two_instance.py
tests/state/test_db_conn.py
tests/state/test_flush_fit.py
tests/state/test_model.py
tests/state/test_write.py
tests/test_fastapi.py
tests/test_simple_pipeline.py

As title. This one is also a breaking PR, so dependencies should be updated.
Closes #209

Adds `props` argument to serve and update ops

---

motion/execute.py
motion/server/update_task.py

Executor only has one update task that processes all update events

---

motion/dicts.py
motion/utils.py

Adding a custom dict import so motion apps are backwards compatible

---

motion/execute.py

Fix bug where forks are happening for no reason

---

motion/server/update_task.py

Log traceback from fit op

---

motion/component.py
motion/execute.py
motion/instance.py
tests/component/test_disabled_instance.py

Configuring caching at the component level.

---

docs/examples/design-patterns.md
motion/component.py
motion/instance.py
tests/component/test_context_manager.py

#207: Allow component instances to be created as context managers.

---

motion/execute.py
motion/server/update_task.py

Putting locks in context managers

---

motion/execute.py
motion/server/update_task.py
motion/utils.py

Lock state writes with timeouts

---

motion/utils.py

Change a logging statement to debug level

---

motion/execute.py
motion/instance.py

Removing info logging statements

---

motion/component.py
motion/execute.py
motion/instance.py
tests/component/test_disabled_instance.py

Adding functionality to disable update processes

---

motion/__init__.py
motion/cli.py
motion/utils.py
tests/state/test_instance_cli.py

Adding functionality to list motion instances

---

motion/execute.py
motion/server/update_task.py

Increase lock timeout to 60 seconds

---

motion/execute.py
motion/server/update_task.py

[Provide a brief description of the changes in this pull request.]
[Link any relevant issues that are addressed in this pull request.]
Please make sure that you have completed the following items before submitting this pull request:
[Add any relevant screenshots or images to help illustrate the changes in this pull request.]
[Add any additional information or context that you feel is important for reviewers to know about this pull request.]

Increase timeout

---

motion/execute.py
motion/instance.py
motion/migrate.py
motion/route.py
motion/utils.py
tests/component/test_context_manager.py
tests/component/test_counter.py
tests/component/test_disabled_instance.py
tests/parallel/test_async.py
tests/state/test_model.py

Running op in main process with force_update

---

motion/execute.py

Minimize race conditions

---

motion/execute.py

Adding force update on regular state update.

---

motion/execute.py

Hold lock while executing saves in motion

---

motion/route.py

Updating pydantic regex param to pattern

---

motion/component.py
motion/execute.py
motion/instance.py

Add helpful error message

---

motion/instance.py
tests/component/test_counter.py

Add default state val

---

motion/execute.py

Only using cached result ops if result is not None.

---

motion/migrate.py
poetry.lock
pyproject.toml

Adding progress bars for migrations.

---

docs/api/state-migrator.md
motion/__init__.py
motion/copy_utils.py

Adding copy utils to allow for import from one Redis DB to another

---

docs/api/state-migrator.md
motion/__init__.py
motion/copy_utils.py

Adding Redisparams to main

---

motion/copy_utils.py
motion/execute.py
motion/migrate.py
motion/server/update_task.py
motion/utils.py

Adding SSL to redis params

---

motion/execute.py
motion/instance.py
motion/mtable.py
tests/conftest.py

Clean up state refreshes

---

motion/execute.py
motion/route.py
motion/server/update_task.py

Adding tracebacks and locking state on creation

---

motion/server/application.py
poetry.lock
pyproject.toml
tests/server/test_simple_server.py

Adds JWT for authentication in motion apps

---

motion/migrate.py

Adding error tracebacks and requiring prod mode to be set for motion

---

motion/component.py

Cleanup should be opt-in

---

motion/cli.py

Adding motionrc default env to dev

---

.github/workflows/ci.yml
Makefile
docs/getting-started/installation.md
motion/__init__.py
poetry.lock
pyproject.toml

This PR creates the optional package add-ons `application` and `table`
Closes #285

Separate optional dependencies

---

motion/execute.py

Deleting multiprocessing values when done

---

motion/execute.py
motion/instance.py
motion/migrate.py
motion/server/update_task.py
tests/parallel/test_async.py
tests/state/test_model.py
tests/test_migrate.py

Change the semantics of forcerefresh

---

docs/api/component.md

Fix mkdocs

---

.github/workflows/publish.yml
Makefile

Fix CD to `npm run build`

---

.github/workflows/publish.yml

Edit CD to trigger on an edit to publish.yml

---

motion/dashboard.py
ui/src/components/DetailComponent.js
ui/src/components/MainContent.js

This PR does the following:
* Prettifies the modal for editing component state
* Adds skeletons to the dashboard
* Modifies the edit component instance state endpoint to only consider _new_ state values from the dashboard

Edit dashboard to work for custom type states.

---

mkdocs.yml
ui/src/App.js
ui/src/components/MotionHeader.js

Prettify dashboard

---

README.md
docs/index.md
pyproject.toml

Edit readme and description

---

docs/api/component-instance.md
motion/instance.py
poetry.lock

Add close as an alias for shutdown

---

motion/instance.py
motion/server/update_task.py
motion/utils.py

Close dangling redis connections
